name: "Collect IPs"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Resolve domains, collect and store IP addresses
        run: |
          python -m pip install dnspython
          python collect-json.py > list.json
          python collect-text.py > list.txt
          python collect-json.py > test.json
          git config --global user.email "vahidfarid@gmail.com"
          git config --global user.name "Vahid Farid"
          git add -A
          git commit -m "Automatic update"
          git push
